# Generated by Django 3.1 on 2020-09-07 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='twitteruser_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='twitteruser_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
